# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/block_design_top/block_design_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top || ORIG_REF_NAME==block_design_top} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_processing_system7_0_0_3/block_design_top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_processing_system7_0_0 || ORIG_REF_NAME==block_design_top_processing_system7_0_0} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_xlslice_0_2/block_design_top_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_xlslice_0_2 || ORIG_REF_NAME==block_design_top_xlslice_0_2} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_xlslice_1_0/block_design_top_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_xlslice_1_0 || ORIG_REF_NAME==block_design_top_xlslice_1_0} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_xlslice_2_0/block_design_top_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_xlslice_2_0 || ORIG_REF_NAME==block_design_top_xlslice_2_0} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_xlslice_0_3/block_design_top_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_xlslice_0_3 || ORIG_REF_NAME==block_design_top_xlslice_0_3} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_task3_0_0/block_design_top_task3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_task3_0_0 || ORIG_REF_NAME==block_design_top_task3_0_0} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_xlconcat_0_0/block_design_top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_xlconcat_0_0 || ORIG_REF_NAME==block_design_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==block_design_top_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/block_design_top_ooc.xdc
