# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.srcs/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0.xci
# IP: The module: 'block_design_top_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_top_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_top_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_top_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.srcs/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0.xci
# IP: The module: 'block_design_top_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_top_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_top_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task3/task3.gen/sources_1/bd/block_design_top/ip/block_design_top_rst_ps7_0_100M_0/block_design_top_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_top_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
