# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/MainDesign/MainDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainDesign || ORIG_REF_NAME==MainDesign} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_BasicLEDController_0_0/MainDesign_BasicLEDController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainDesign_BasicLEDController_0_0 || ORIG_REF_NAME==MainDesign_BasicLEDController_0_0} -quiet] -quiet

# XDC: c:/Users/Jenny2/Documents/02Semester/FPGA_lab/task2/task2.gen/sources_1/bd/MainDesign/MainDesign_ooc.xdc
